name: "Setup Node.js and Run Tests"
description: "A composite action to install dependencies and run tests"

inputs:
  node-version:
    description: "Node.js version to use"
    required: true
    default: "18"

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install dependencies
      run: npm install
      shell: bash

    - name: Run tests
      run: npm test
      shell: bash
