name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use custom setup-node action
        uses: ./.github/actions/setup-node

      - name: Install dependencies
        run: npm install

      - name: Run Node App
        run: npm start
